# Generated by Django 3.0.4 on 2020-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_headers', models.CharField(default='SOME STRING', max_length=999)),
                ('req_cookies', models.CharField(default='SOME STRING', max_length=999)),
                ('req_url', models.CharField(default='SOME STRING', max_length=999)),
                ('req_method', models.CharField(default='SOME STRING', max_length=20)),
                ('resp_headers', models.CharField(default='SOME STRING', max_length=999)),
                ('resp_body', models.CharField(default='SOME STRING', max_length=999)),
                ('resp_cookies', models.CharField(default='SOME STRING', max_length=999)),
                ('resp_status', models.CharField(default='SOME STRING', max_length=999)),
                ('res_RTT', models.CharField(default='SOME STRING', max_length=999)),
            ],
        ),
    ]
