# Generated by Django 3.0.4 on 2020-04-10 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='usertype',
            name='fo',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='app01.Foo'),
            preserve_default=False,
        ),
    ]
